### ISSUE TITLE
Modifiers only working in else part of if snippet when used in multiTV input

### ISSUE THREAD

**Issue by leonie12** [extras-evolution/multiTV#18]
I am not sure if it is if snippet or multiTV which is the reason for this issue. Therefore I post it also here:

[https://github.com/evolution-cms/evolution/issues/351](https://github.com/evolution-cms/evolution/issues/351)

**Comment by 64j** [comment]
@leonie12 
still works

![image](https://user-images.githubusercontent.com/4653189/32701436-72aa93f8-c7e6-11e7-8002-1f8218be43bd.png)

**Comment by leonie12** [comment]
Does it really work for you? What I see in your screenshot seems to be the &else case (winter) which works also for me. The issue is with the &then part (summer), which should deliver evo-logo-1280x395.jpg etc in your setup.

**Comment by 64j** [comment]
@leonie12 

**condition**
```
[[if?is=`[*season*]:=:summer`&then=`assets/images/evo-logo.png`&else=`assets/images/modx-logo.png`]]
```


switch summer
![image](https://user-images.githubusercontent.com/4653189/32701680-07735854-c7eb-11e7-9340-f4047b846dc4.png)


switch winter
![image](https://user-images.githubusercontent.com/4653189/32701687-19b8b8ba-c7eb-11e7-942f-65fbe605c721.png)

**Comment by 64j** [comment]
@leonie12 
not work for **summer**
So?

**Comment by leonie12** [comment]
For me it does not work. Where is the difference between your and my setup? Which versions of multiTV and if snippet are you using?
Any idea what else could be the issue?

**Comment by 64j** [comment]
@leonie12 
while I see the problem in the IF snippet

**Comment by leonie12** [comment]
Can be. But why does it work for you?

**Comment by leonie12** [comment]
I tried it with replacing if snippet with phx call like this:
`[*phx:if=`[*season*]`:is=`summer`:then=`assets/images/header/summer.jpg`:else=`assets/images/header/winter.jpg`*]`

The result is the same: Works also here only for else case.

**Comment by 64j** [comment]
@leonie12 
no, look at the screenshots, it does not work for **summer**

**Comment by leonie12** [comment]
Sorry I did not regard the screenshot well enough.
See my last comment above.

It seems that if snippet is not the (only) issue.

**Comment by 64j** [comment]
@leonie12 

code phx modificator
add **$output = $modx->evalSnippets($output);**

pathFilename
```php
<?php

$output = $modx->evalSnippets($output);
$path_parts = pathinfo($output);
echo $path_parts['dirname'] . '/' . $path_parts['filename'];
```

extension
```php
<?php

$output = $modx->evalSnippets($output);
$extension = pathinfo($output, PATHINFO_EXTENSION);
echo $extension;
```

**Comment by leonie12** [comment]
Tried it. No success.

**Comment by 64j** [comment]
@leonie12 
it's impossible

so everything works for me

**Comment by leonie12** [comment]
Sorry, you are right.
I had the if snippet call uncached. This did not work. After changing it to uncached it works now with your assitions to the modifiers as expected.
Many thanks.

Btw.: The if snippet calls in the multiTV inputs for title and alt text have to be uncached to not deliver empty results …

**Comment by 64j** [comment]
@leonie12 
you pass the snippet to the modifier, and expect that it will be treated as a string.
I added the line in the code to process the snippet

You can close the question.
