### ISSUE TITLE
Documentation missing :(

### ISSUE THREAD

**Issue by fourroses666** [extras-evolution/multiTV#21]
https://web.archive.org/web/20170713062515/http://jako.github.io/multiTV/

https://web.archive.org/web/20170213112551/http://jako.github.io:80/multiTV/snippet/

**Comment by pmfx** [comment]
Thats bad. There still is http://docs.evo.im/en/03_extras/multitv.html and http://www.evolution-docs.com/extras/multitv/

**Comment by fourroses666** [comment]
Thats good enouf! Didn't check that.
