### ISSUE TITLE
PHP7.2 count() issue

### ISSUE THREAD

**Issue by scendstudio** [extras-evolution/multiTV#47]
We're using Evo 1.4.6. Our host just upgraded to PHP7.2 and it triggered the error below when the multiTV variable is empty, when there are fields then it only outputs the first one.

Trying to get property 'action' of non-object
« Evo Parse Error »
Error : count(): Parameter must be an array or an object that implements Countable
File	/httpd.www/assets/tvs/multitv/includes/multitv.class.php
Line	1089
Source	$countOutput = count($tvOutput);
Current Snippet	multiTV

**Comment by scendstudio** [comment]
To resolve the error for now I changed line 1089 to:
$countOutput = is_array($tvOutput) && count($tvOutput);

But I don't know if that's the best way or not... it still only outputs the first result, I'm not sure how to resolve that.

**Comment by dmi3yy** [comment]
can you check now

on my site work with:
- empty 
- 1 results
- 3 results

**Comment by scendstudio** [comment]
Works perfectly now, thanks!
