### ISSUE TITLE
Multitv dont work (bug)?

### ISSUE THREAD

**Issue by Sybrenb** [extras-evolution/multiTV#53]
My multitv doesn't seem to work anymore. It worked fine and the content will still show up on the website, but the input field are all empty. Also when I try to add content to the empty multitv fields it won't save.

How can I fix this? Updating multitv doesn't seem to work or fix the problem.

**Comment by Deesen** [comment]
Which versions do you use for

- Evolution
- PHP

And then, if you edit a resource, is there any error-message in browser-console? If so, please provide it.
