### ISSUE TITLE
Endless loading dbtable display

### ISSUE THREAD

**Issue by Neoziox** [extras-evolution/multiTV#59]
Hi!

PHP 7.0.33
Evo 1.4.9
multiTV 2.0.15

This function of multiTV is very usefull. I love it. Have a personal DB and manage it with a TV. But it doesn't work anymore. Even with the demo file dbtabledemo.config.json the table is loaded endlessly. Help!

Thanks.

**Comment by Neoziox** [comment]
Same problem with 2.0.0 RC. Please help me!

**Comment by mnoskov** [comment]
Sholud be fixed, can you check it?

**Comment by Neoziox** [comment]
Wonderful! Thanks a lot! You are my saviour!

**Comment by Neoziox** [comment]
Can I be curious and ask what was the origin of the issue?

**Comment by mnoskov** [comment]
Don't know, I think it was changed template rendering behaviour caused by api mode development. I just added the api mode defenition.

**Comment by Neoziox** [comment]
Same issue (again) on 2.0.1 (after an update, maybe that is problematic).
