### ISSUE TITLE
PHP 8.0 error

### ISSUE THREAD

**Issue by fourroses666** [extras-evolution/multiTV#71]
« Evolution CMS Parse Error »

Error : Undefined array key "templates"

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /www/assets/tvs/multitv/includes/multitv.class.php
Line | 270
Source | $this->templates = $settings[$this->tvTemplates];

**Comment by fourroses666** [comment]
Can't reproduce it anymore. Will close this for now..

**Comment by fourroses666** [comment]
I can reproduce but don't know whats the issue.

**Comment by fourroses666** [comment]
It might be something else. When I

**Comment by mplavala** [comment]
> 

This is known and fixed DocLister issue, use Extras to update DocLister. Maybe on the other install you do not call DocLister (or not in the same context) and so the issue does not come up.

**Comment by fourroses666** [comment]
I did update DocLister and reinstalled/upgraded EVO, maybe some other plugin is giving issues. Can't look further into this for now. Will close it again and investigate some other time again.
